black7375/Firefox-UI-Fix

- README.org
There were some unnatural grammar usage in the documentation and the name of this project is incorrectly displayed at the end of it(It's displayed as Proton Fix, which is the old name) . 
I suggest you to change the directory tree of this repo to be easier to install this theme. (What I mean by that is to move the .css files and /icons folder to a new directory called `chrome`.)
> minor fixes in documentation

- userChrome.css
This change makes the icons in the More Tools menu look correct regardless of whether "Enable browser chrome and add-on debugging toolboxes" is disabled. It does this by assigning the latter half of the icons via `nth-last-child()` so that if the 2 lines are absent from the menu, the icons for those positions get overruled by the correct ones. If the two lines _are_ present, their icons are not overruled.
> Fixes #36: wrong icons under More Tools if debugging is disabled

- .gitattributes
With this `.gitattributes` file, the `.github` folder and some other unnecessary files will be excluded from the git zip archive to make the installation cleaner.
> ref: Exclude unnecessary files from zip export

- userContent.css
This adds some missing errors to the restored error pages. Most of them were taken from the original `aboutNetError.css`.
> Added missing errors

- userChrome.css
On Windows 10 and Original Lepton, There is a bug on sharing icon, so I fixed and made pull request.
> fix: Fix sharing icon is not aligned

- README.org
Emphasis on the "not" differentiates it from the "WHY Proton"-heading
> "WHY Not Proton" -> "Why NOT Proton"

- userContent.css
SUMO has a few portions that were not fixed for themes (in dark mode white-on-white), and others that did not play nice with themes. For the former, a robust solution is in this pull request. For the latter, it only works via an invert(0.5) so that the tools are gray.
From
To
- PR Type
- Distribution
(Should work on all, I am only making pull for original right now)
N/A
> Misc. fixes for SUMO (support.mozilla.org)

- userContent.css
Fixes unreadable/white text on Add-On Developer Hub website. (Note that dark mode is still not implemented.)
Fixes #365 (at least text visibility part).
<details>
</details>
<details>
</details>
- PR Type
- Distribution
- (applies to all distributions)
> Fix: Unreadable text on Add-on Developer Hub

- css/leptonChrome.css
- src/rounding/_square.scss
Allow squaring of next, previous and close findbar buttons, as I do not believe these can be squared currently.
Tested on MacOS 12.3.1 - Waterfox G5.0.1.
- PR Type
- Distribution
> Allow squaring of additional findbar buttons

- CREDITS
- css/leptonContent.css
- src/contents/_activity_stream.scss
- user.js
Add the ability to hide Firefox's logo in Firefox Home (e.g. about:home and about:newtab)
- PR Type
- Distribution
> Add: FFHome - Add the ability to hide Firefox's logo

- css/leptonContent.css
- src/contents/_activity_stream.scss
The child component of `search-inner-wrapper` div is a button in the new searchbar (instead of the input textfield), so this PR just add a small change to make highlight works on both old and new searchbar.
**PR Type**
Before
After
> Fix: Activity Stream - Enable Hover Highlights on the New Fake Searchbar

- css/leptonChrome.css
- css/leptonContent.css
- src/contents/_rounding.scss
- src/leptonContent.scss
- src/rounding/_dialog.scss
- src/rounding/_index.scss
- src/rounding/_square.scss
Add rounding support for the new migration wizard and firefox view infoboxes, fix the clear history infobox not working if summoned from the menu bar
**PR Type**
#645
> Fix: Rounding - New migration wizard, firefox view, clear history

- css/leptonChrome.css
- src/padding/_panel.scss
add compact mode support for the unified extensions panel
**PR Type**
#711
before:
after:
> Add: Padding - Unified extensions panel with compact mode

- css/leptonChrome.css
- css/leptonChromeESR.css
- src/icons/fork_browsers/_floorp.scss
Fixed folder icons not showing up in 'Open Profile Directory' in Floorp browser's application menu.
**PR Type**
Current
Expected behavior
I'm an amateur, so I may have missed some points to fix.
> Fix: folder icons in 'Open Profile Directory' in Floorp browser's application menu

- userChrome.css
Fix double separators [#764](https://github.com/black7375/Firefox-UI-Fix/issues/764)
**PR Type**
> Fix double separators when removing Set as Desktop Background menu item

- css/leptonChrome.css
- css/leptonChromeESR.css
- css/leptonContent.css
- css/leptonContentESR.css
- src/contents/_activity_stream.scss
Removes image context menu entries when right-clicking on the background image.
**PR Type**
#773
> Fix: Activity Stream - Use pseudo-element for background image

- css/leptonChrome.css
- css/leptonChromeESR.css
- src/compatibility/_theme.scss
My OS theme is `Breeze / Adwaita`, and it looks like this:
(It seems to be working relatively well)
`AccentColor` is currently being applied.
```css
#star-button[sttared] {
fill-opacity: 1;
fill: var(--tolbarbutton-icon-fill-attention);
}
:root:-moz-lwtheme {
--download-progress-fill-color: var(--lwt-toolbarbutton-icon-fill-attention, light-dark(rgb(0, 97, 224), rgb(0, 221, 255)));
}
:root:-moz-lwtheme {
--toolbarbutton-icon-fill-attention: var(--lwt-toolbarbutton-icon-fill-attention, light-dark(rgb(0, 97, 224), rgb(0, 221, 255)));
}
root:-moz-lwtheme {
--lwt-toolbarbutton-icon-fill-attention: var(--button-primary-bgcolor, rgb(0, 120, 215));
}
```
We can resolve the issue by removing the code that was causing the compatibility issue.
**PR Type**
#791 …
> Fix: Compatibility - Icon fill color #791

- css/leptonChrome.css
- css/leptonChromeESR.css
- src/theme/proton_chrome/_page_info.scss
Calculate page info's tab height.
**PR Type**
#780
- before
- after
> Fix: Proton - MacOS page info icons cut off #780

- css/leptonChrome.css
- css/leptonChromeESR.css
- src/padding/_tabbar_width.scss
Floorp Injection. The old code causes breaking Floorp's multirow-tabs (Paxmod)
**PR Type**
#777
https://github.com/black7375/Firefox-UI-Fix/assets/73892113/2c14bad3-76b7-49f8-a88b-78ba5080e685
The issue should not be closed immediately after the merge, as there may be other code causing this problem. I will carry on research this issue.
> fix: Compatibility with multirow-tab

- css/leptonChrome.css
- css/leptonChromeESR.css
- src/tab/_container_tab.scss
- user.js
Currently the length of the container line in a tab changes dynamically, which can be highly distracting for some users. This PR adds an option, defaulted to off, to disable that behavior.
**PR Type**
> Add: Tabbar - Container always long option

- css/leptonChrome.css
- css/leptonChromeESR.css
- src/tab/_selected_tab.scss
- src/tab/selected_tab/_supernova_like_contextline.scss
- fixed contextline's position is lower in container-tabs.
- fixed contextline animation is not working on container-tabs.
**PR Type**
none
Contextline Position:
|Before|
|---|
|![Screenshot From 2025-05-11 01-16-10](https://github.com/user-attachments/assets/f07534c9-5a46-47e8-9e91-123f58c1d6ce)|
|After|
|---|
|![Screenshot From 2025-05-11 01-11-03](https://github.com/user-attachments/assets/9d8379c8-20e2-4de3-a518-6a03a6716937)|
Animation:
|Before|
|---|
|![output_before](https://github.com/user-attachments/assets/06acd91f-6036-4f87-8ce5-74e0cbd75239)|
|After|
|---|
|![output_after](https://github.com/user-attachments/assets/0b6c7164-1f0c-46bd-8706-90087f0ed12c)|
Contextline color synced with theme (Firefox Alpenglow):
|After|
|---| …
> Fix: Tab - Supernova Contextline Position/Animation in container-tabs
