- userChrome.css
> Fix: Panel - Fix text cut off in some language #28

- README.org
I have improved the install instructions, because they were a little bit unclear (to me at least)
> Improves install instructions

- .gitattributes
- README.org
The documentation is kinda erred in some places and I smoothed them out.<br>The .gitattributes file has additions so the user will have only the essential stuff. (Sorry I typed this out on an iPod)
> Docfix(grammar and sentence structure) and .gitattributes polish

- userChrome.css
This is my code change like https://github.com/black7375/Firefox-UI-Fix/issues/101#issuecomment-872907372
But I don't have Mac and Linux computer, So I can't check on any other environment.
> Fix: Popup Panel - Fix panel on compact mode #101

- README.org
Fix various spelling mistakes in README (by running through a spell checker).
N/A
Check like `- [x]`.
- PR Type
- Distribution
N/A
> Fix typos in README

- install.sh
Ask user if they installed git.
Add "Did you install git?" to OS NOT DETECTED error message.
If applicable, add screenshots to help explain your commit.
`FAILED: OS NOT DETECTED, couldn't install required packages` -> `OS NOT DETECTED, couldn't install required packages. Please manually install git.`
Check like `- [x]`.
- PR Type
- Distribution
Add any other context about the commit here.
> Improve lepton_error_message OS NOT DETECTED

- install.sh
A clear and concise description of what the PR is.
If applicable, add screenshots to help explain your commit.
Check like `- [x]`.
- PR Type
- Distribution
Add any other context about the commit here.
> Add support for FireDragon browser

- userChrome.css
Solves Bug #180 
If applicable, add screenshots to help explain your commit.
Check like `- [x]`.
- PR Type
- Distribution
> Fix: `menu` padding issue fixed #180

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
Commenting out explanatory text to avoid reading it when people forget to remove it before posting
**Related Issue** 
https://github.com/black7375/Firefox-UI-Fix/issues/197
- PR Type
> Commenting out, grammar, "get GTK-theme" added

- .github/ISSUE_TEMPLATE/feature_request.md
In case people leave it in
See https://github.com/black7375/Firefox-UI-Fix/issues/197
- PR Type
- Distribution
> Explanatory text commented out

- install.ps1
- install.sh
Just a small adjustment that corrects two typos and changes the wording of "Now backup" to "Now making a backup".
> Fix typos and small grammar change

- install.sh
The PR simply changes the wording of the ``echo`` at the start of the multiselect function
No related issues
N/A
- PR Type
- Distribution
N/A
> changed multiselect wording and removed '!'s on install.sh

- userContent.css
I noticed more things that  were problematic and fixable, like being able to see the username menu
- PR Type
- Distribution
As last time, the change is across the board
> More SUMO Fixes

- userContent.css
Certain dialog boxes in SUMO were not fixed. AMO/developers was missing fixes. Now accounts.firefox.org (I stupidly called it AMO too lol)
- PR Type
- Distribution
Will work on every one
N/A
> SUMO and AMO Fixes

- userContent.css
I was looking at some SUMO Forums and needed to view a KB article before it was verified.
The editor was in light mode.
Also the scrollbars were off
I could not attach, will try in a comment
- PR Type
- Distribution
> SUMO KB editor fixes

- src/icons/_layout_menu.scss
See https://github.com/black7375/Firefox-UI-Fix/issues/363
https://github.com/black7375/Firefox-UI-Fix/issues/363
- PR Type
- Distribution
> https://github.com/black7375/Firefox-UI-Fix/issues/363

- .github/ISSUE_TEMPLATE/bug_report.md
Added a spoiler in the user.js setup section of the bug issue template, since its really long
**Environment:**
- PR Type
I got tired of scrolling
> Add a spoiler in the `user.js setup` part of the issue template

- user.js
- PR Type
- [x ] `Fix:` Bug fix or change default values.
- Distribution
- [ x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
> Remove quote

- css/leptonChrome.css
- src/rounding/_square.scss
- user.js
New option `userChrome.rounding.square_dialog` for dialogs (close confirmation, etc.)
**PR Type**
> Add: Rounding - Dialog

- css/leptonContent.css
- src/contents/_rounding.scss
- src/contents/proton_contents/_proton_commons.scss
- src/leptonContent.scss
Add current (tables & cards are still round) rounding options into about pages (Does not work inside page dialogs)
**PR Type**
Fixes #586
> Add: Rounding - Square options in about pages

- css/leptonChrome.css
- src/rounding/_square.scss
Radio buttons should be round
**PR Type**
Fixes #600
> Fix: Rounding - Remove radio button

- css/leptonChrome.css
- css/leptonContent.css
- src/contents/_rounding.scss
- src/library/_proton.scss
- src/rounding/_square.scss
- src/theme/proton_chrome/_page_info.scss
Dialogs now support the rounding options
**PR Type**
Fixes #598, fixes #601
> Fix: Rounding - Square options in dialogs

- css/leptonContent.css
- src/contents/_rounding.scss
various fixes for rounding options in content
**PR Type**
each issue references the issue it fixes
> Rounding fixes

- css/leptonChrome.css
- css/leptonContent.css
- src/contents/_proton_contents.scss
- src/contents/_rounding.scss
- src/contents/proton_contents/_about_preferences.scss
- src/rounding/_square.scss
Rounding fixes and add warning icon to the sanitize history dialog
**PR Type**
Fixes #621, fixes #632, fixes #636, fixes #637, fixes #638, fixes #639
> Some more fixes

- css/leptonContent.css
- src/contents/_rounding.scss
rounded corners support for pdfs
**PR Type**
#647
> Fix: Rounding - PDF

- css/leptonChrome.css
- css/leptonContent.css
- src/contents/_rounding.scss
- src/rounding/_square.scss
Dialogs' matching now uses regex in case there may be more of them in the future
**PR Type**
#645, #649
> Fix rounding for dialogs & firefox view

- css/leptonContent.css
- src/contents/_rounding.scss
fixes the new addons toggle button for v111
**PR Type**
#667
> Fix: Rounding - Addons toggle button

- README.org
NOTE: I replaced the three dots “...” with horizontal ellipsis Unicode character “…” in the README.org file, so if there would be character encoding problems, then reverse this change.
If you dislike this change, then don't approve the commit, and if you like it, then please don't mark me as contributor, because I don't deserve the contributor place.
Some little changes to the README.org file.
**PR Type**
> Added missing punctuation, and some tweaks to README.org

- css/leptonChrome.css
- css/leptonContent.css
- src/contents/_rounding.scss
- src/rounding/_square.scss
- user.js
adds the `userChrome.rounding.square_infobox` option
**PR Type**
#645 #618 #616
> Add: Rounding - Square infoboxes

- css/leptonChrome.css
- css/leptonContent.css
- src/contents/_rounding.scss
- src/padding/_menu.scss
fix translations table and menu popup padding
I didn't touch migration wizard in #713, because I can't tell what density is in use from content
**PR Type**
#713, #718
> Translations fixes

- src/autohide/sidebar/_overlap.scss
Fixed a typo in a CSS selector.
**PR Type**
> Fix a typo

- css/leptonChrome.css
- css/leptonChromeESR.css
- src/padding/_panel.scss
- src/rounding/_index.scss
- src/rounding/_round.scss
Fixes the menu button not being rounded on windows and having bigger padding
**PR Type**
#735
> Unified extensions menu button fixes

- userChrome.css
All rules & selectors have an unnecessary prefix that must be removed to be used. Better to remove only comment start and end lines, for cleaner diffs when comparing one's own version against updates.
**PR Type**
> Better diff for userChrome.css

- user.js
With the ESR 115 release the preferences are no longer necessary.
**PR Type**
> Cleanup user.js.

- install.sh
Adjusted calls for setting ini variables to not skip everything after first whitespace as well as adjusted method of reading ini file to not skip them.
**PR Type**
#840 
> fix: Profile path no longer being cut off on space

- css/leptonChrome.css
- css/leptonChromeESR.css
- src/tab/_selected_tab.scss
- src/tab/selected_tab/_supernova_like_contextline.scss
- user.js
add thunderbird supernova-like contextline for selected tab.
**PR Type**
none
animation for contextline:
Added option `userChrome.tab.supernova_like_contextline`.
It is not allowed to be used at the same time as `userChrome.tab.photon_like_contextline`, as this would cause conflicts.
It is also not intended to be used in the Photon style.
Supernova is another name for Thunderbird 115.
It has many improvements and a new tab design.
This is a PR to make that tab design available in Firefox as well.
The following links will help you with the Supernova tab design and other information.
[Getting Started With The Main Window Of Thunderbird 115](https://blog.thunderbird.net/2023/07/getting-started-with-the-main-window-of …
> Add: Tab - Supernova like Selected Tab ContextLine

- install.sh
Hi! This PR added the path of Flatpak version of LibreWolf. Thanks!
**PR Type**
> feat: add librewolf flatpak profile path
